import { LevelData } from "../types";

export const LEVELS: LevelData[] = [
    {
        item_name: "그냥 대머리",
        item_desc: "방금 밀었다. 광택 없음. 만지면 까칠함.",
        cost: 100,
        price: 0,
        success_msg: "깔끔하게 밀렸다. 시작이 반이다.",
        success_rate: 1,
        maintain_rate: 0,
        fail_rate: 0,
    },
    {
        item_name: "감자 머리",
        item_desc: "그냥 평범한 대머리. 동글동글하니 귀엽다.",
        cost: 200,
        price: 10,
        success_msg: "오, 불 켜졌다. 전기세 굳음.",
        maintain_msg: "미끄러짐. 기스는 안 남.",
        fail_msg: "너무 닦아서 벗겨짐. 으악.",
        success_rate: 0.9,
        maintain_rate: 0.1,
        fail_rate: 0,
    },
    {
        item_name: "발광 머리",
        item_desc: "자체 발광 시작. 형광등 필요 없음.",
        cost: 500,
        price: 50,
        success_msg: "천사냐? 머리 위에 링 떴다.",
        maintain_msg: "빛이 안 뭉침. 다시.",
        fail_msg: "눈부셔서 헛침. 뚝배기 깨짐.",
        success_rate: 0.8,
        maintain_rate: 0.2,
        fail_rate: 0,
    },
    {
        item_name: "엔젤링",
        item_desc: "착한 사람 눈에만 보임. 주차장 프리패스상.",
        cost: 1000,
        price: 300,
        success_msg: "껍질 벗긴 듯한 매끈함. 소금 찍고 싶다.",
        maintain_msg: "안 먹힘. 머리가 너무 단단함.",
        fail_msg: "마력 과다. 머리 터짐.",
        success_rate: 0.7,
        maintain_rate: 0.25,
        fail_rate: 0.05,
    },
    {
        item_name: "삶은 달걀",
        item_desc: "흰자 같은 피부. 모공이 사라졌다.",
        cost: 3000,
        price: 1500,
        success_msg: "딱! 소리가 경쾌하다. 4구, 3구 가능.",
        maintain_msg: "덜 익음. 반숙이라 광이 안 남.",
        fail_msg: "껍질 까다가 흰자까지 뜯김.",
        success_rate: 0.65,
        maintain_rate: 0.3,
        fail_rate: 0.05,
    },
    {
        item_name: "당구공",
        item_desc: "플라스틱 질감. 부딪치면 '딱' 소리 남.",
        cost: 8000,
        price: 5000,
        success_msg: "구멍 3개 뚫림. 기름칠한 듯 번들거린다.",
        maintain_msg: "삑사리 남. 초크 칠하고 다시.",
        fail_msg: "당구대에 찍힘. 흠집 나서 폐기.",
        success_rate: 0.6,
        maintain_rate: 0.3,
        fail_rate: 0.1,
    },
    {
        item_name: "볼링공",
        item_desc: "묵직하다. 굴리면 스트라이크.",
        cost: 15000,
        price: 50000,
        success_msg: "조개껍데기의 영롱함. 바다 냄새 난다.",
        maintain_msg: "손가락 빠짐. 안 빠져서 강화 실패.",
        fail_msg: "도랑(Gutter)으로 빠짐. 꽝.",
        success_rate: 0.55,
        maintain_rate: 0.35,
        fail_rate: 0.1,
    },
    {
        item_name: "진주",
        item_desc: "인간이 만들어낸 보석. 우아함 그 자체.",
        cost: 25000,
        price: 120000,
        success_msg: "뱀파이어가 싫어함. 차가운 금속성.",
        maintain_msg: "모래알 들어감. 표면이 거칠다.",
        fail_msg: "가짜였음. 플라스틱이라 녹아버림.",
        success_rate: 0.5,
        maintain_rate: 0.4,
        fail_rate: 0.1,
    },
    {
        item_name: "은구슬",
        item_desc: "은도금 완료. 독이 닿으면 색이 변함.",
        cost: 40000,
        price: 350000,
        success_msg: "누런 빛깔! 이제야 돈 냄새가 난다.",
        maintain_msg: "녹슬었음. 치약으로 닦아야 함.",
        fail_msg: "찌그러짐. 쇠구슬 됨.",
        success_rate: 0.45,
        maintain_rate: 0.4,
        fail_rate: 0.15,
    },
    {
        item_name: "금구슬",
        item_desc: "24K 순금. 이빨로 깨물지 마시오.",
        cost: 60000,
        price: 800000,
        success_msg: "얼굴이 비친다. 미래지향적 디자인.",
        maintain_msg: "금박 벗겨짐. 도금이었냐?",
        fail_msg: "금값이 너무 올라서 팔아버림(실패).",
        success_rate: 0.4,
        maintain_rate: 0.45,
        fail_rate: 0.15,
    },
    {
        item_name: "크롬 두피",
        item_desc: "얼굴 비침. 지문 묻으면 티 확 남.",
        cost: 90000,
        price: 2_500_000,
        success_msg: "미러볼 등판. 춤추고 싶어지는 비주얼.",
        maintain_msg: "도금 벗겨짐. 락카칠 다시 해야 함.",
        fail_msg: "부식됨. 고물상에 팔아야 할 판.",
        success_rate: 0.35,
        maintain_rate: 0.45,
        fail_rate: 0.2,
    },
    {
        item_name: "미러볼",
        item_desc: "360도 회전 중. 파티의 주인공.",
        cost: 120000,
        price: 5_000_000,
        success_msg: "세상에서 제일 단단함. 드릴도 안 먹힘.",
        maintain_msg: "모터 고장. 회전을 멈춤.",
        fail_msg: "깨짐. 7년 동안 재수 없을 예정.",
        success_rate: 0.3,
        maintain_rate: 0.5,
        fail_rate: 0.2,
    },
    {
        item_name: "다이아몬드",
        item_desc: "경도 MAX. 긁히지 않는 자존심.",
        cost: 160000,
        price: 12_000_000,
        success_msg: "이제 실체도 없음. 그냥 빛 그 자체.",
        maintain_msg: "너무 단단해서 가공 불가.",
        fail_msg: "금 갔음. 가격 폭락.",
        success_rate: 0.25,
        maintain_rate: 0.5,
        fail_rate: 0.25,
    },
    {
        item_name: "홀로그램",
        item_desc: "만져지지 않음. 물리 공격 무효화.",
        cost: 200000,
        price: 30_000_000,
        success_msg: "눈에서 빔 나감. 라식 수술 가능.",
        maintain_msg: "배터리 방전. 흐릿해짐.",
        fail_msg: "서버 오류. 404 Not Found.",
        success_rate: 0.2,
        maintain_rate: 0.55,
        fail_rate: 0.25,
    },
    {
        item_name: "레이저",
        item_desc: "고출력 빔 발사. 산 하나 삭제.",
        cost: 250000,
        price: 70_000_000,
        success_msg: "에너지 덩어리. 만지면 감전됨.",
        maintain_msg: "과열됨. 냉각수 부어서 진정시킴.",
        fail_msg: "출력 조절 실패. 장비 다 터짐.",
        success_rate: 0.15,
        maintain_rate: 0.55,
        fail_rate: 0.3,
    },
    {
        item_name: "플라즈마",
        item_desc: "고체, 액체, 기체도 아님. 제4의 상태.",
        cost: 350000,
        price: 150_000_000,
        success_msg: "지구 탈출. 이제 우주 쓰레기... 아니 위성.",
        maintain_msg: "자기장 불안정. 찌릿찌릿함.",
        fail_msg: "폭발. 실험실 날아감.",
        success_rate: 0.12,
        maintain_rate: 0.58,
        fail_rate: 0.3,
    },
    {
        item_name: "인공위성",
        item_desc: "대기권 돌파. GPS 신호 잡힘.",
        cost: 450000,
        price: 500_000_000,
        success_msg: "꼬리 달림. 소원 빌면 들어줄지도?",
        maintain_msg: "궤도 이탈. 통신 두절.",
        fail_msg: "추락. 대기권에서 타버림.",
        success_rate: 0.1,
        maintain_rate: 0.55,
        fail_rate: 0.35,
    },
    {
        item_name: "혜성",
        item_desc: "얼음과 먼지의 덩어리. 속도 개빠름.",
        cost: 600000,
        price: 1_500_000_000,
        success_msg: "토끼가 방아 찧는 중. 밤에만 보임.",
        maintain_msg: "태양풍 맞고 녹을 뻔.",
        fail_msg: "충돌. 공룡 멸종 시나리오.",
        success_rate: 0.08,
        maintain_rate: 0.52,
        fail_rate: 0.4,
    },
    {
        item_name: "달 (Moon)",
        item_desc: "곰보 자국 있음. 밀물 썰물 조종함.",
        cost: 800000,
        price: 5_000_000_000,
        success_msg: "악 눈부셔! 님 그냥 '태양' 그 자체임.",
        maintain_msg: "지구 그림자에 가려짐. 월식 발생.",
        fail_msg: "깨짐. 지구 멸망 확정.",
        success_rate: 0.05,
        maintain_rate: 0.5,
        fail_rate: 0.45,
    },
    {
        item_name: "태양신",
        item_desc: "생명체 아님. 불타는 별. 가까이 오면 녹음.",
        cost: 1_000_000,
        price: 50_000_000_000,
        success_msg: "모든 빛을 흡수함. 탈모의 끝은 어둠.",
        maintain_msg: "흑점 폭발. 통신 장애.",
        fail_msg: "초신성 폭발. 다 같이 죽자.",
        success_rate: 0.03,
        maintain_rate: 0.47,
        fail_rate: 0.5,
    },
    {
        item_name: "블랙홀",
        item_desc: "빛조차 탈출 불가. 압도적 흡입력.",
        cost: Number.MAX_SAFE_INTEGER,
        price: 0,
        success_msg: "최종 단계!",
        maintain_msg: undefined,
        fail_msg: "빅뱅. 우주 리셋.",
        success_rate: 0.95,
        maintain_rate: 0,
        fail_rate: 0.05,
    },
];
