import { LevelData } from "../types";

export const LEVELS: LevelData[] = [
    {
        item_name: "그냥 대머리",
        item_desc: "방금 밀었다. 광택 없음. 만지면 까칠함.",
        cost: 100,
        price: 0,
        click_gold: 24,
        success_msg: "깔끔하게 밀렸다. 시작이 반이다.",
        maintain_msg: undefined,
        fail_msg: undefined,
        success_rate: 1,
        maintain_rate: 0,
        fail_rate: 0,
    },
    {
        item_name: "감자 머리",
        item_desc: "그냥 평범한 대머리. 동글동글하니 귀엽다.",
        cost: 140,
        price: 100,
        click_gold: 50,
        success_msg: "밭에서 캐왔다. 구수한 흙냄새.",
        maintain_msg: "미끄러짐. 기스는 안 남.",
        fail_msg: "너무 닦아서 벗겨짐. 으악.",
        success_rate: 0.95,
        maintain_rate: 0.05,
        fail_rate: 0,
    },
    {
        item_name: "삶은 달걀",
        item_desc: "흰자 같은 피부. 모공이 사라졌다.",
        cost: 350,
        price: 240,
        click_gold: 124,
        success_msg: "껍질 완벽하게 까짐. 소금 뿌려야지.",
        maintain_msg: "덜 익음. 반숙이라 광이 안 남.",
        fail_msg: "껍질 까다가 흰자까지 뜯김.",
        success_rate: 0.9,
        maintain_rate: 0.1,
        fail_rate: 0,
    },
    {
        item_name: "찐빵",
        item_desc: "김이 모락모락. 겨울철 최애 간식.",
        cost: 700,
        price: 652,
        click_gold: 240,
        success_msg: "호호 불어 먹어야 함.",
        maintain_msg: "앙꼬는 없음. 종이가 달라붙음.",
        fail_msg: "안 떨어짐. 찌그러짐. 납작 만두 됨.",
        success_rate: 0.85,
        maintain_rate: 0.15,
        fail_rate: 0,
    },
    {
        item_name: "찹쌀떡",
        item_desc: "말랑말랑함. 꼬집어보고 싶은 볼살.",
        cost: 2100,
        price: 1447,
        click_gold: 722,
        success_msg: "쫀득함 2배! 모공까지 쫀쫀해짐.",
        maintain_msg: "너무 질척거림. 손에 다 묻음.",
        fail_msg: "굳음. 돌덩이 됨.",
        success_rate: 0.8,
        maintain_rate: 0.2,
        fail_rate: 0,
    },
    {
        item_name: "젤리 푸딩",
        item_desc: "찰랑거림. 스치면 흔들림.",
        cost: 5600,
        price: 3947,
        click_gold: 1926,
        success_msg: "젤리 컬러. 극강의 부드러움.",
        maintain_msg: "무너짐. 숟가락으로 퍼먹힘.",
        fail_msg: "엎어짐. 접시에서 탈출.",
        success_rate: 0.75,
        maintain_rate: 0.25,
        fail_rate: 0,
    },
    {
        item_name: "물방울떡",
        item_desc: "투명함 100 %. 있는 듯 없는 듯.",
        cost: 10500,
        price: 10947,
        click_gold: 3614,
        success_msg: "미즈신겐모찌. 맑고 깨끗하고 자신 있게.",
        maintain_msg: "증발함. 수증기 됨.",
        fail_msg: "터짐. 그냥 물웅덩이 됨.",
        success_rate: 0.7,
        maintain_rate: 0.3,
        fail_rate: 0,
    },
    {
        item_name: "군밤",
        item_desc: "노릇노릇한 갈색. 윤기가 좔좔 흐름.",
        cost: 17500,
        price: 24756,
        click_gold: 6024,
        success_msg: "약단밤 스타일. 아주 잘 구워짐.",
        maintain_msg: "너무 구워서 탐. 숯덩이 됨.",
        fail_msg: "터짐. 껍질 파편 튐.",
        success_rate: 0.6,
        maintain_rate: 0.35,
        fail_rate: 0.05,
    },
    {
        item_name: "진주",
        item_desc: "인간이 만들어낸 보석. 우아함 그 자체.",
        cost: 28000,
        price: 49073,
        click_gold: 15000,
        success_msg: "조개껍데기의 영롱함. 바다 냄새 난다.",
        maintain_msg: "모래 씹힘. 표면이 거칠다.",
        fail_msg: "가짜였음. 플라스틱이라 녹아버림.",
        success_rate: 0.57,
        maintain_rate: 0.37,
        fail_rate: 0.06,
    },
    {
        item_name: "은구슬",
        item_desc: "은도금 완료. 독이 닿으면 색이 변함.",
        cost: 42000,
        price: 92149,
        click_gold: 36000,
        success_msg: "뱀파이어가 싫어함. 차가운 금속성.",
        maintain_msg: "녹슬었음. 치약으로 닦아야 함.",
        fail_msg: "찌그러짐. 쇠구슬 됨.",
        success_rate: 0.54,
        maintain_rate: 0.39,
        fail_rate: 0.07,
    },
    {
        item_name: "금구슬",
        item_desc: "24K 순금. 이빨로 깨물지 마시오.",
        cost: 63000,
        price: 168531,
        click_gold: 100000,
        success_msg: "누런 빛깔! 이제야 돈 냄새가 난다.",
        maintain_msg: "금박 벗겨짐. 도금이었냐?",
        fail_msg: "금값이 너무 올라서 팔아버림(실패).",
        success_rate: 0.51,
        maintain_rate: 0.41,
        fail_rate: 0.08,
    },
    {
        item_name: "크롬 두피",
        item_desc: "얼굴 비침. 지문 묻으면 티 확 남.",
        cost: 84000,
        price: 294531,
        click_gold: 240000,
        success_msg: "얼굴이 비친다. 미래지향적 디자인.",
        maintain_msg: "도금 벗겨짐. 락카칠 다시 해야 함.",
        fail_msg: "부식됨. 고물상에 팔아야 할 판.",
        success_rate: 0.48,
        maintain_rate: 0.43,
        fail_rate: 0.09,
    },
    {
        item_name: "루비",
        item_desc: "붉은 보석. 정열적인 빨간 머리(?).",
        cost: 112000,
        price: 481198,
        click_gold: 38554,
        success_msg: "불타는 듯한 적색. 시선 강탈.",
        maintain_msg: "흠집 남. 보석 감정가 하락.",
        fail_msg: "깨짐. 붉은 파편이 튀움.",
        success_rate: 0.45,
        maintain_rate: 0.45,
        fail_rate: 0.1,
    },
    {
        item_name: "다이아몬드",
        item_desc: "경도 MAX. 긁히지 않는 자존심.",
        cost: 140000,
        price: 747864,
        click_gold: 1500000,
        success_msg: "세상에서 제일 단단함. 드릴도 안 먹힘.",
        maintain_msg: "너무 단단해서 가공 불가.",
        fail_msg: "금 갔음. 가격 폭락.",
        success_rate: 0.42,
        maintain_rate: 0.47,
        fail_rate: 0.11,
    },
    {
        item_name: "발광 머리(Move)",
        item_desc: "자체 발광 시작. 형광등 필요 없음.",
        cost: 175000,
        price: 1147864,
        click_gold: 60240,
        success_msg: "오, 불 켜졌다. 전기세 굳음.",
        maintain_msg: "빛이 안 뭉침. 건전지 다 됐나 ?",
        fail_msg: "눈부셔서 헛침. 전구 깨짐.",
        success_rate: 0.4,
        maintain_rate: 0.45,
        fail_rate: 0.15,
    },
    {
        item_name: "홀로그램",
        item_desc: "만져지지 않음. 물리 공격 무효화.",
        cost: 245000,
        price: 1662573,
        click_gold: 3600000,
        success_msg: "이제 실체도 없음. 그냥 빛 그 자체.",
        maintain_msg: "배터리 방전. 흐릿해짐.",
        fail_msg: "서버 오류. 404 Not Found.",
        success_rate: 0.36,
        maintain_rate: 0.44,
        fail_rate: 0.2,
    },
    {
        item_name: "플라즈마",
        item_desc: "고체, 액체, 기체도 아님. 제4의 상태.",
        cost: 315000,
        price: 2479240,
        click_gold: 24000000,
        success_msg: "에너지 덩어리. 만지면 감전됨.",
        maintain_msg: "자기장 불안정. 찌릿찌릿함.",
        fail_msg: "폭발. 실험실 날아감.",
        success_rate: 0.32,
        maintain_rate: 0.43,
        fail_rate: 0.25,
    },
    {
        item_name: "달(Moon)",
        item_desc: "곰보 자국 있음. 밀물 썰물 조종함.",
        cost: 420000,
        price: 4054240,
        click_gold: 600000000,
        success_msg: "토끼가 방아 찧는 중. 밤에만 보임.",
        maintain_msg: "지구 그림자에 가려짐. 월식 발생.",
        fail_msg: "깨짐. 지구 멸망 확정.",
        success_rate: 0.28,
        maintain_rate: 0.42,
        fail_rate: 0.3,
    },
    {
        item_name: "태양신",
        item_desc: "생명체 아님. 불타는 별. 가까이 오면 녹음.",
        cost: 560000,
        price: 7284954,
        click_gold: 2400000000,
        success_msg: "악 눈부셔! 님 그냥 '태양' 그 자체임.",
        maintain_msg: "흑점 폭발. 통신 장애.",
        fail_msg: "초신성 폭발. 다 같이 죽자.",
        success_rate: 0.24,
        maintain_rate: 0.41,
        fail_rate: 0.35,
    },
    {
        item_name: "엔젤링",
        item_desc: "신의 영역 직전. 성스러운 고리.",
        cost: 700000,
        price: 12375863,
        click_gold: 240962,
        success_msg: "천사냐 ? 머리 위에 링 떴다.",
        maintain_msg: "고리가 자꾸 떨어짐. 사이즈 미스.",
        fail_msg: "타락함. 링 깨지고 악마 됨.",
        success_rate: 0.2,
        maintain_rate: 0.4,
        fail_rate: 0.4,
    },
    {
        item_name: "대머리 신",
        item_desc: "갓(God). 눈부신 후광 그 자체.",
        cost: Number.MAX_SAFE_INTEGER,
        price: 0,
        click_gold: Number.MAX_SAFE_INTEGER,
        success_msg: "대머리계의 절대자. 털을 창조함.",
        maintain_msg: undefined,
        fail_msg: "신들의 전쟁. 패배하고 소멸함.",
        success_rate: 0.01,
        maintain_rate: 0.49,
        fail_rate: 0.5,
    },
];